---
- name: install remire repository
  yum: 
     name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     state: present

- name: Add remi-php55
  yum_repository:
    name: remi-php55
    description: Remi's PHP 55 RPM repository for Enterprise Linux $releasever - $basearch
    mirrorlist: http://rpms.remirepo.net/enterprise/$releasever/php55/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: install needed packages
  yum: 
     name: 
     - php 
     - php-mcrypt 
     - php-cli 
     - php-gd 
     - php-curl 
     - php-mysql 
     - php-ldap 
     - php-zip 
     - php-fileinfo 
     - php-xml.x86_64 
     - php7-fpm 
     - php-intl 
     - php-pear 
     - php-devel 
     - gcc 
     - gcc-cpp 
     - gcc-c++ 
     - php-mbstring 
     - php-xmlrpc 
     - php-soap 
     - php-opcache
     - unzip
   notify: "restart mariadb"
